#pragma once
#include "pch.h"

#define CORE_OFFSET_LIST(X) \
	X(ProcessEvent) \
	X(ProcessEventVFT) \
	X(GUObjectArray) \
	X(GWorld) \
	X(GEngine) \
	X(GIsClient) \
	X(GIsServer) \
	X(FMemory_Free) \
	X(FMemory_Realloc) \
	X(ChangeGameSessionId) \
	X(StaticFindObject) \
	X(StaticLoadObject) \
	X(StaticConstructObject_Internal) \
	X(TickFlush) \
	X(InternalServerTryActivateAbilityVFT) \
	X(GHandle) \
	X(AbilitySpecDefaultConstructor) \
	X(AbilitySpecClassConstructor) \
	X(AbilitySpecCDOConstructor) \
	X(ABuildingActor_OnDamageServer) \
	X(ABuildingActor_PostUpdateVFT) \
	X(ABuildingActor_ServerOnAttemptInteractVFT) \
	X(ABuildingActor_HandleDamagedVFT) \
	X(SpawnActor) \
	X(FFrame__CurrentNativeFunction) \
	X(FFrame__PropertyChainForCompiledIn) \
	X(FFrame__Next) \
	X(Step) \
	X(StepExplicitProperty) \
	X(ExecFunction) \
	X(FName_AppendString) \
	X(FName_ToStringOut) \
	X(FName_Compare) \
	X(FName_GetComparisonNameEntry) \
	X(FName_Constructor1) /* const char* Str */ \
	X(UObjectBase_AddObject) \
	X(UObjectBase_AtomicallyClearFlags) \
	X(UObjectBase_DeferredRegister) \
	X(UObjectBase_EmitBaseReferences) \
	X(UObjectBase_IsValidLowLevel) \
	X(UObjectBase_IsValidLowLevelFast) \
	X(UObjectBase_LowLevelRename) \
	X(UObjectBase_Register) \
	X(UObjectBase_Destructor) \
	X(UObjectBaseUtility_AddToCluster) \
	X(UObjectBaseUtility_CanBeInCluster) \
	X(UObjectBaseUtility_GetFullName) \
	X(UObjectBaseUtility_GetFullName_1) \
	X(UObjectBaseUtility_GetInterfaceAddress) \
	X(UObjectBaseUtility_GetLinker) \
	X(UObjectBaseUtility_GetLinkerIndex) \
	X(UObjectBaseUtility_GetNativeInterfaceAddress) \
	X(UObjectBaseUtility_IsDefaultSubobject) \
	X(UObject_BeginDestroy) \
	X(UObject_FinishDestroy) \
	X(UObject_DefaultConstructor) \
	X(UObject_GetDefaultSubobjects) \
	X(UObject_GetDefaultSubobjectByName) \
	X(UObject_PostInitProperties) \
	X(UObject_PostLoadVFT) \
	X(UObject_FindFunctionChecked) \
	X(UObject_GetWorldVFT) \
	X(UObject_NeedsLoadForClientVFT) \
	X(UObject_CanCreateInCurrentContext) \
	X(UField_GetOwnerClass) \
	X(UField_GetOwnerStruct) \
	X(UStruct_FindPropertyByName) \
	X(UStruct__SuperStruct) \
	X(UStruct__Children) \
	X(UStruct__PropertiesSize) \
	X(UStruct__MinAlignment) \
	X(UClass_FindFunctionByName) \
	X(UClass_GetSparseClassData) \
	X(FName_GetPlainNameString1) \
	X(FName_GetPlainNameString2) \
	X(UProperty__Offset_Internal) \
	X(UProperty__ElementSize) \
	X(UProperty__PropertyFlags) \
	X(UField__Next) \
	X(UField__Name) \
	X(UBoolProperty__FieldMask) \
	X(UEngine_BroadcastNetworkFailure) \
	X(UEngine_BroadcastNetworkLagStateChanged) \
	X(UEngine_CancelAllPending) \
	X(UEngine_CreateGameUserSettings) \
	X(UEngine_GetFirstGamePlayer) \
	X(UEngine_GetNetMode) \
	X(UEngine_GetMaxTickRate) \
	X(UEngine_GetMaxTickRateVFT) \
	X(UEngine_CreateNetDriver) \
	X(UEngine_LoadMap) \
	X(UEngine_LoadMapVFT) \
	X(UEngine_CreateNamedNetDriver) \
	X(UEngine_GetWorldContextFromWorldChecked) \
	X(UEngine_FindNamedNetDriver) \
	X(UEngine_DestroyNamedNetDriver) \
	X(UEngine_GetWorldContextFromWorld) \
	X(UEngine_CreateNewWorldContext) \
	X(UEngine_CreateNetDriver_Local) \
	X(UWorld_AddController) \
	X(UWorld_AddLevel) \
	X(UWorld_AddNetworkActor) \
	X(UWorld_AddStreamingLevel) \
	X(UWorld_AddToWorld) \
	X(UWorld_AllowLevelLoadRequests) \
	X(UWorld_AreActorsInitialized) \
	X(UWorld_AreAlwaysLoadedLevelsLoaded) \
	X(UWorld_BeginPlay) \
	X(UWorld_CommitMapChange) \
	X(UWorld_ConditionallyCreateDefaultLevelCollections) \
	X(UWorld_ContainsActor) \
	X(UWorld_ContainsLevel) \
	X(UWorld_CreateAISystem) \
	X(UWorld_GetActiveLevelCollection) \
	X(UWorld_GetActorCount) \
	X(UWorld_GetAddressURL) \
	X(UWorld_GetDefaultGravityZ) \
	X(UWorld_GetFirstLocalPlayerFromController) \
	X(UWorld_GetFirstPlayerController) \
	X(UWorld_GetGameViewport) \
	X(UWorld_GetGravityZ) \
	X(UWorld_GetMapName) \
	X(UWorld_GetTimerManager) \
	X(UWorld_GetWorldSettings) \
	X(UWorld_K2_GetWorldSettings) \
	X(UWorld_HasBegunPlay) \
	X(UWorld_InternalGetNetMode) \
	X(UWorld_IsGameWorld) \
	X(UWorld_IsInSeamlessTravel) \
	X(UWorld_IsServer) \
	X(UWorld_MarkObjectsPendingKill) \
	X(UWorld_RemoveActor) \
	X(UWorld_RemoveController) \
	X(UWorld_RemoveNetworkActor) \
	X(UWorld_SeamlessTravel) \
	X(UWorld_ServerTravel) \
	X(UWorld_SetGameMode) \
	X(UWorld_SetGameState) \
	X(UWorld_SetNavigationSystem) \
	X(UWorld_WelcomePlayer) \
	X(UWorld_UpdateStreamingLevelShouldBeConsidered) \
	X(UWorld_FindCollectionByType) \
	X(UWorld__NextSwitchCountdown) \
	X(UWorld_ListenPatch) \
	X(UWorld_RemovePIEPrefix) \
	X(FGuid_ToString) \
	X(UGameInstance_StartGameInstance) \
	X(UGameInstance_Shutdown) \
	X(UGameInstance_GetFirstLocalPlayerController) \
	X(UGameInstance_ClientTravelToSession) \
	X(UGameInstance_CleanupGameViewport) \
	X(AActor_ActorHasTag) \
	X(AActor_CallPreReplication) \
	X(AActor_CheckStillInWorld) \
	X(AActor_ClearCrossLevelReferences) \
	X(AActor_CopyRemoteRoleFrom) \
	X(AActor_Destroy) \
	X(AActor_DisableInput) \
	X(AActor_EnableInput) \
	X(AActor_ExchangeNetRoles) \
	X(AActor_FindOrAddNetworkObjectInfo) \
	X(AActor_InternalGetNetMode) \
	X(AActor_IsPendingKillPending) \
	X(AActor_HasNetOwner) \
	X(AActor_HasLocalNetOwner) \
	X(AActor_SetNetDormancy) \
	X(AActor_BeginPlay) \
	X(AActor_BeginPlayVFT) \
	X(AActor_ResetVFT) \
	X(AGameSession_ApproveLogin) \
	X(AGameSession_AtCapacity) \
	X(AGameSession_GetSessionJoinability) \
	X(AGameSession_KickPlayer) \
	X(AGameSession_KickPlayerVFT) \
	X(AGameSession_ReturnToMainMenuHost) \
	X(AGameSession_UnregisterPlayer) \
	X(AGameSession_UpdateSessionJoinability) \
	X(AGameSession_InitOptions) \
	X(AGameSession_RegisterPlayer) \
	X(AGameSession__NextPlayerID) \
	X(AGameSession_ProcessAutoLogin) \
	X(AGameSession_OnAutoLoginComplete) \
	X(AGameSession_UnregisterPlayer_1) \
	X(AGameSession_UnregisterPlayers) \
	X(AGameSession_GetPlayerControllerFromNetId) \
	X(AGameModeBase_InitGame) \
	X(AGameModeBase_InitGameVFT) \
	X(AGameModeBase_InitGameState) \
	X(AGameModeBase_InitGameStateVFT) \
	X(AGameModeBase_CanServerTravel) \
	X(AGameModeBase_SpawnDefaultPawnFor) \
	X(AGameModeBase_SpawnDefaultPawnAtTransform) \
	X(AGameModeBase_RestartPlayer) \
	X(AGameModeBase_FinishRestartPlayer) \
	X(AGameModeBase_FinishRestartPlayerVFT) \
	X(AGameModeBase_HandleStartingNewPlayer) \
	X(AGameModeBase_SpawnPlayerController) \
	X(AGameModeBase_SpawnPlayerControllerVFT) \
	X(AGameModeBase_GetGameSessionClass) \
	X(AGameModeBase_GetGameSessionClassVFT) \
	X(AGameModeBase_ProcessServerTravelVFT) \
	X(UKismetStringLibrary_Conv_StringToName) \
	X(AGameMode_AddInactivePlayer) \
	X(AGameMode_AddInactivePlayerVFT) \
	X(AGameMode_Broadcast) \
	X(AGameMode_BroadcastLocalized) \
	X(AGameMode_EndMatch) \
	X(AGameMode_FindInactivePlayer) \
	X(AGameMode_GetNetworkNumber) \
	X(AGameMode_HandleMatchHasEndedVFT) \
	X(AGameMode_HandleMatchHasStartedVFT) \
	X(AGameMode_HandleMatchIsWaitingToStart) \
	X(AGameMode_HandleSeamlessTravelPlayer) \
	X(AGameMode_HandleStartingNewPlayer) \
	X(AGameMode_InitSeamlessTravelPlayer) \
	X(AGameMode_IsHandlingReplays) \
	X(AGameMode_OnMatchStateSet) \
	X(AGameMode_PlayerCanRestart) \
	X(AGameMode_PostSeamlessTravel) \
	X(AGameMode_ReadyToStartMatch) \
	X(AGameMode_RestartGame) \
	X(AGameMode_Say) \
	X(AGameMode_SendPlayer) \
	X(AGameMode_SetMatchState) \
	X(AGameMode_SetSeamlessTravelViewTarget) \
	X(AGameMode_StartMatch) \
	X(AGameMode_StartPlay) \
	X(AGameMode_OverridePlayerState) \
	X(AGameMode_PostLogin) \
	X(AGameMode_Logout) \
	X(AGameMode_CanServerTravel) \
	X(AGameMode_InitGame) \
	X(APlayerController_HasClientLoadedCurrentWorld) \
	X(APlayerController_ServerAcknowledgePossession) \
	X(UGameMapsSettings_GetGameModeForName) \
	X(ULevelStreaming_PostLoad) \
	X(ULevelStreaming_DetermineTargetState) \
	X(ULevelStreaming_OnLevelAdded) \
	X(ULevelStreaming_IsDesiredLevelLoaded) \
	X(ULevelStreaming_SetLevelLODIndex) \
	X(ULevelStreaming_SetPriority) \
	X(ULevelStreaming_SetWorldAsset) \
	X(ULevelStreaming_GetWorldAssetPackageName) \
	X(ULevelStreaming_GetWorldAssetPackageFName) \
	X(ULevelStreaming_RenameForPIE) \
	X(ULevelStreaming_ShouldBeVisible) \
	X(ULevelStreaming_IsStreamingStatePending) \
	X(ULevelStreaming_CreateInstance) \
	X(ULevelStreaming_RequestLevel) \
	X(ULevelStreaming_SetLoadedLevel) \
	X(ULevelStreaming_DiscardPendingUnloadLevel) \
	X(ULevel_SortActorList) \
	X(ULevel_InitializeNetworkActors) \
	X(ULevel_ClearActorsSeamlessTraveledFlag) \
	X(ULevel_SetWorldSettings) \
	X(ULevel_IsNetActor) \
	X(ULevel_PostInitProperties) \
	X(ULevel_BeginDestroy) \
	X(ULevel_FinishDestroy) \
	X(ULevel_PostLoad) \
	X(ULevel_CreateCluster) \
	X(ULevel_ClearLevelComponents) \
	X(ULevel_UpdateLevelComponents) \
	X(ULevel_IncrementalUpdateComponents) \
	X(ULevel_IncrementalUnregisterComponents) \
	X(UActorComponent_RegisterComponentWithWorld) \
	X(ULevel_RouteActorInitialize) \
	X(ULevel_ApplyWorldOffset) \
	X(ULevel_RegisterActorForAutoReceiveInput) \
	X(ULevel_PushPendingAutoReceiveInput) \
	X(FURL_IsInternal) \
	X(FURL_IsLocalInternal) \
	X(FURL_HasOption) \
	X(FURL_GetOption) \
	X(FURL_AddOption) \
	X(FURL_RemoveOption) \
	X(FURL_ToString) \
	X(FURL_GetHostPortString) \
	X(FWorldContext_SetCurrentWorld) \
	X(FWorldContext__ThisCurrentWorld) \
	X(UNetDriver_InitListen) \
	X(UNetDriver_InitListenVFT) \
	X(UNetDriver_SetWorld) \
	X(UNetDriver_SetWorldVFT) \
	X(UNetDriver_TickFlush) \
	X(UNetDriver_IsServerVFT) \
	X(UNetDriver_IsLevelInitializedForActorVFT) \
	X(FParse_Param) \
	X(AFortGameMode_OnInitWorldRecordComplete) \
	X(AFortGameMode_OnEndOfDay) \
	X(AFortGameMode_SetCurrentPlaylistNameVFT) \
	X(AFortGameMode_InitGame) \
	X(AFortGameMode_RestartPlayer) \
	X(AFortGameMode_FinishRestartPlayer) \
	X(AFortGameMode_SpawnDefaultPawnFor) \
	X(AFortGameMode_SetCurrentPlaylistIdVFT) \
	X(AFortGameMode_FinishWorldInitializationVFT) \
	X(AFortGameMode_PickTeam) \
	X(AFortGameMode_PickTeamVFT) \
	X(AFortGameMode_ProcessServerTravelPatch1) \
	X(AFortGameMode_InitializeTeams) \
	X(AFortGameMode_InitializeTeamsVFT) \
	X(AFortGameMode_PlacePlayerOnTeamVFT) \
	X(AFortWorldManager_HandleWorldQueryComplete) \
	X(AFortGameModeZone_CheckForAllPlayersIn) \
	X(AFortGameModeZone_RemoveKnownPlayer) \
	X(AFortGameModeZone_UpdateSessionForMatchmaking) \
	X(AFortGameModeZone_NotifyPendingConnectionLost) \
	X(AFortGameModeZone_OnZoneEnd) \
	X(AFortGameModeZone_DoLogoutAnalytics) \
	X(AFortGameModeZone_HandleMatchHasStarted) \
	X(AFortGameModeZone_HandleMatchHasEnded) \
	X(AFortGameModeZone_DoInitialRestartAnalytics) \
	X(AFortGameModeZone_InitGame) \
	X(AFortGameModeZone_InitGameState) \
	X(AFortGameModeZone_ChoosePlayerStart) \
	X(AFortGameModeZone_CreateAIDirector) \
	X(AFortGameModeZone_CreateAIDirectorVFT) \
	X(AFortGameModeZone_CreateAIGoalManager) \
	X(AFortGameModeZone_CreateAIGoalManagerVFT) \
	X(AFortGameModeAthena_SetCurrentPlaylistId) \
	X(AFortGameModeAthena_SetTimeOfDayManagerGameplayOverride) \
	X(AFortGameModeAthena_OnPlaylistDataLoaded) \
	X(AFortGameModeAthena_ApplyPlaylistDataTables) \
	X(AFortGameModeAthena_OnDedicatedServerRestarting) \
	X(AFortGameModeAthena_SpawnInitialSafeZone) \
	X(AFortGameModeAthena_AttemptChangeTeam) \
	X(AFortGameModeAthena_PickTeam) \
	X(AFortGameModeAthena_HandleMatchHasStarted) \
	X(AFortGameModeAthena_FinishRestartPlayer) \
	X(AFortGameModeAthena_StartMatchAbandonProcess) \
	X(AFortGameModeAthena_OnMatchAbandonTimeout) \
	X(AFortGameModeAthena_CheckWinConditionLastManStanding) \
	X(AFortGameModeAthena_GrantVictoryToAllRemainingTeams) \
	X(AFortGameModeAthena_GrantVictoryForNumTeamsAndEndGame) \
	X(AFortGameModeAthena_GrantLossToAllRemainingTeams) \
	X(AFortGameModeAthena_GrantLossToAllTeams) \
	X(AFortGameModeAthena_GrantLosses) \
	X(AFortGameModeAthena_ChoosePlayerStart_Creative) \
	X(AFortGameModeAthena_StartWarmupPhase) \
	X(AFortGameModeAthena_UpdateWarmupPhase) \
	X(AFortGameModeAthena_StartAircraftPhase) \
	X(AFortGameModeAthena_StartSafeZonesPhase) \
	X(AFortGameModeAthena_IsSafeZoneAllowed) \
	X(AFortGameModeAthena_StartEndGamePhase) \
	X(AFortGameModeAthena_StartEndGamePhaseTeam) \
	X(AFortGameModeAthena_CreateAIDirector) \
	X(AFortGameModeAthena_PostReloadConfig) \
	X(AFortGameModeAthena_ReadyToStartMatch) \
	X(AFortGameModeAthena_InitGame) \
	X(AFortGameModeAthena_InitGameState) \
	X(AFortGameModeAthena_SpawnDefaultPawnFor) \
	X(AFortGameModeAthena_RestartPlayer) \
	X(AFortGameModeAthena_FinishWorldInitialization) \
	X(AFortGameModeAthena_AddToAlivePlayers) \
	X(AFortGameModeAthena_RemoveFromAlivePlayers) \
	X(AFortGameModeAthena_PlacePlayerOnTeam) \
	X(AFortGameModeAthena_OnGivenMatchAssignmentVFT) \
	X(AFortGameModeAthena_SpawnFortSpawnActors) \
	X(AFortGameStateAthena_OnRep_CurrentPlaylistInfo) \
	X(AFortGameStateAthena_OnPlaylistDataLoadCompleted) \
	X(AFortGameStateAthena_UpdatePlaylistDependentData) \
	X(AFortGameStateAthena_LoadCurrentPlaylistData) \
	X(UFortPlaylistManager_InitializePlaylists) \
	X(UReplicationDriver_ServerReplicateActors) \
	X(UReplicationDriver_ServerReplicateActorsVFT) \
	X(UFortReplicationGraph_Enabled) \
	X(UAbilitySystemComponent_ClientActivateAbilityFailed) \
	X(UAbilitySystemComponent_InternalTryActivateAbility) \
	X(UAbilitySystemComponent_GiveAbility) \
	X(UAbilitySystemComponent_GiveAbilityAndActivateOnce) \
	X(UAbilitySystemComponent_FindAbilitySpecFromHandle) \
	X(ULevelStreamingDynamic_LoadLevelInstance) \
	X(ULevelStreamingDynamic_LoadLevelInstanceBySoftObjectPtr) \
	X(ABuildingFoundation_SelectAndSetupMyBuildingLevel) \
	X(ABuildingFoundation_StreamInMyBuilding) \
	X(UFortKismetLibrary_CanPlaceBuildableClassInStructuralGrid) \
	X(UFortKismetLibrary_GetWeaponStatsRow) \
	X(FRotator_Quaternion) \
	X(ABuildingSMActor_ReplaceBuildingActor) \
	X(ABuildingSMActor_ReplaceBuildingActorVFT) \
	X(ABuildingSMActor_PostUpdate) \
	X(ABuildingSMActor_SetEditingPlayer) \
	X(ABuildingSMActor_SetEditingPlayerVFT) \
	X(ABuildingSMActor_PostLoad) \
	X(AFortPickup_FinishedTargetSpline) \
	X(AFortPickup_ForceFinishedTargetSpline) \
	X(AFortPickup_SetPickupTarget) \
	X(AFortPickup_UpdateSpecialActorStat) \
	X(AFortPickup_GivePickupTo) \
	X(AFortPickup_GivePickupToVFT) \
	X(AFortPickup_SetupForMovementCompToss) \
	X(AFortPickup_SetPickupItems) \
	X(AFortPickup_SetPickupItemsVFT) \
	X(AFortPlayerPawn_ForceFinishIncomingPickups) \
	X(AFortPlayerPawn_ForceFinishIncomingPickupsVFT) \
	X(AFortPlayerPawn_OnRep_ZiplineState) \
	X(AFortQuickBars_GetFocusedQuickBar) \
	X(ABuildingContainer_SpawnLootVFT) \
	X(ABuildingContainer_ServerOnAttemptInteract) \
	X(AFortInventory_Destroyed) \
	X(AFortInventory_DumpInventoryToLog) \
	X(AFortInventory_GetInventoryCapacity) \
	X(AFortInventory_GetOverflowFromAddingItem) \
	X(AFortInventory_GetOverflowFromAddingItemInNewStack) \
	X(AFortInventory_GetInventoryUsed) \
	X(AFortInventory_GetOverflowFromAddingItemInExistingStack) \
	X(AFortInventory_InitializeExistingItem) \
	X(AFortInventory_GetMaxStackSize) \
	X(UKismetSystemLibrary_GetEngineVersion) \
	X(UKismetSystemLibrary_ExecuteConsoleCommand) \
	X(UPlayer_GetPlayerController) \
	X(UPlayer_SwitchController) \
	X(UNetConnection_IsNetReady) \
	X(UNetConnection_IsNetReadyVFT) \
	X(UNetConnection_GetUChildConnectionVFT) \
	X(UNetConnection_FindActorChannelRef) \
	X(UNetDriver__ReplicationFrame) \
	X(UNetDriver_GetNetMode) \
	X(UNetDriver__NetworkObjects) \
	X(UNetDriver_IsAdaptiveNetUpdateFrequencyEnabled) \
	X(UNetDriver__NetTag) \
	X(UNetDriver__DestroyedStartupOrDormantActors) \
	X(UNetDriver_IsLevelInitializedForActor) \
	X(UNetDriver__DebugRelevantActors) \
	X(UNetDriver__LastPrioritizedActors) \
	X(UNetDriver__LastRelevantActors) \
	X(UNetDriver__LastSentActors) \
	X(UNetDriver__LastNonRelevantActors) \
	X(UNetDriver__GuidCache) \
	X(UNetDriver_TickDispatch) \
	X(UNetDriver__SendCycles) \
	X(UNetDriver__RecvCycles) \
	X(UNetDriver__LastTickDispatchRealtime) \
	X(UNetDriver__bIsStandbyCheckingEnabled) \
	X(UNetDriver__bHasStandbyCheatTriggered) \
	X(UNetDriver__JoinInProgressStandbyWaitTime) \
	X(UNetDriver__StandbyRxCheatTime) \
	X(UNetDriver__StandbyTxCheatTime) \
	X(UNetDriver__BadPingThreshold) \
	X(UNetDriver__PercentMissingForRxStandby) \
	X(UNetDriver__PercentMissingForTxStandby) \
	X(UNetDriver__PercentForBadPing) \
	X(APlayerController_GetViewTarget) \
	X(APlayerController_SendClientAdjustment) \
	X(APlayerController_SendClientAdjustmentVFT) \
	X(FNetworkObjectList_Remove) \
	X(FNetworkObjectList_ClearRecentlyDormantConnection) \
	X(FNetworkObjectList_Add) \
	X(UNetConnection__ActorChannels) \
	X(UNetConnection__TimeSensitive) \
	X(UNetConnection__TickCount) \
	X(UNetConnection__State) \
	X(UNetConnection__DestroyedStartupOrDormantActors) \
	X(UNetConnection__ClientWorldPackageName) \
	X(UNetConnection__ClientVisibleLevelNames) \
	X(UNetConnection_CreateChannel) \
	X(UNetConnection_SendChallengeControlMessage) \
	X(UNetConnection_CleanUp) \
	X(UNetConnection_CleanUpVFT) \
	X(UNetConnection__LastRecvAckTime) \
	X(UActorChannel__LastUpdateTime) \
	X(UActorChannel__RelevantTime) \
	X(UActorChannel_Close) \
	X(UActorChannel_StartBecomingDormant) \
	X(UActorChannel_SetChannelActorForDestroy) \
	X(UActorChannel_SetChannelActor) \
	X(UActorChannel_ReplicateActor) \
	X(FNetViewer_Constructor) \
	X(AActor_GetNetPriority) \
	X(AActor_GetNetPriorityVFT) \
	X(AActor_IsRelevancyOwnerFor) \
	X(AActor_IsRelevancyOwnerForVFT) \
	X(AActor_IsNetRelevantFor) \
	X(AActor_IsNetRelevantForVFT) \
	X(AActor_GetWorld) \
	X(AActor__CreationTime) \
	X(AActor_PreInitializeComponents) \
	X(AActor_PreInitializeComponentsVFT) \
	X(AActor_TickVFT) \
	X(AActor_PostInitializeComponentsVFT) \
	X(AFortPoiVolume_OverlapsPawn) \
	X(FDebug_AssertFailed) \
	X(UWorld__TimeSeconds) \
	X(FOutBunch_Constructor) \
	X(FNetGUIDCache_SupportsObject) \
	X(UObject_GetArchetypeFromRequiredInfo) \
	X(UChannel__NumInRec) \
	X(UChannel__NumOutRec) \
	X(UChannel_SendBunch) \
	X(UChannel_SendBunchVFT) \
	X(UChannel_Close) \
	X(UChannel_CloseVFT) \
	X(UChannel_StartBecomingDormantVFT) \
	X(AFortGameSession_ValidatePlayer) \
	X(AFortGameSession_CreateServerGame) \
	X(UPackageMap_WriteObject) \
	X(CollectGarbage) \
	X(CollectGarbageInternal) \
	X(AFortPlayerControllerAthena_ClientRestart) \
	X(AFortPlayerControllerAthena_SpawnQuickBars) \
	X(AFortPlayerControllerAthena_SetupQuickBars) \
	X(AFortGameState_ApplyHomebaseEffectsOnPlayerSetup) \
	X(AFortGameState_ApplyHomebaseEffectsOnPlayerSetupVFT) \
	X(UMcpProfileGroup_SendRequestNow) \
	X(AFortPlayerPawn_ServerChoosePart) \
	X(AFortPlayerState_InitializeHero) \
	X(AFortPlayerState_RefreshCharacterCustomization) \
	X(AFortPlayerState_ApplyCharacterCustomization) \
	X(FString_Append) \
	X(FString_AppendInt) \
	X(FString_ToBool) \
	X(AFortPlayerController_OnReadyToStartMatch) \
	X(AFortPlayerController_OnReadyToStartMatchVFT) \
	X(AFortPlayerController_SpawnQuickBarsVFT) \
	X(AFortPlayerController_SetupQuickBarsVFT) \
	X(AFortPlayerController_RemoveInventoryItem) \
	X(AFortPlayerController_RemoveInventoryItemVFT) \
	X(AFortPlayerController_CanAffordToPlaceBuildableClass) \
	X(AFortPlayerController_CanAffordToPlaceBuildableClassVFT) \
	X(AFortPlayerController_PayBuildableClassPlacementCost) \
	X(AFortPlayerController_PayBuildableClassPlacementCostVFT) \
	X(AFortPlayerController_PayBuildingRepairCost) \
	X(AFortPlayerController_GetPlayerViewPoint) \
	X(AFortPlayerControllerZone_OnReadyToStartMatch) \
	X(AFortPlayerControllerZone_ClientOnPawnDied) \
	X(AFortGameStateZone_ApplyHomebaseEffectsOnPlayerSetup) \
	X(AActor_GetNetOwnerVFT) \
	X(UFortWorldItemDefinition_ServerExecuteVFT) \
	X(UFortWeaponItemDefinition_GetMaxDurability) \
	X(UFortWeaponItemDefinition_GetMaxDurabilityVFT) \
	X(UFortWorldItem_SetOwningInventory) \
	X(UFortWorldItem_SetOwningInventoryVFT) \
	X(UFortWorldItem_SetLoadedAmmoVFT) \
	X(UFortWorldItem_SetPhantomReserveAmmoVFT) \
	X(UFortWorldItem_SetInInventoryOverflowVFT) \
	X(UFortWorldItem_SetDurabilityVFT) \
	X(UFortControllerComponent_Aircraft_EnterAircraft) \
	X(AController_InitPlayerState) \
	X(AController_InitPlayerStateVFT) \
	X(AController_GetPlayerViewPointVFT) \
	X(AController_Reset) \
	X(UFortAnalytics_SetGameSessionID) \
	X(UFortAnalytics_SetGameStateClassName) \
	X(AFortGameSessionDedicated_FinalizeCreation) \
	X(AFortGameSessionDedicated_FinalizeCreationPatch1) \
	X(AFortGameSessionDedicated_FinalizeCreationVFT) \
	X(AFortGameSessionDedicated_OnUpdateComplete) \
	X(AFortGameSessionDedicated_OnAllPlayersUnregistered) \
	X(AFortGameSessionDedicated_OnServerConfigurationRequest) \
	X(AFortGameSessionDedicated_OnServerConfigurationRequestVFT) \
	X(FFortBaseWeaponStats_GetDurability) \
	X(UNavigationSystem_CreateNavigationSystem) \
	X(FDedicatedServerUrlContext_Constructor) \
	X(UFortQuestManager_SendCustomStatEvent) \
	X(UFortQuestManager_QueueStatEvent) \
	X(UFortQuestManager_SendStatEvent) \
	X(UFortQuestManager_ProcessPendingStatEvents) \
	X(BeginLoad) \
	X(EndLoad) \
	X(UGameplayAbility_CanActivateAbility) \
	X(UGameplayAbility_CanActivateAbilityVFT) \
	X(UFortGameInstance_ServerTravel) \
	X(FMsg_Logf) \
	X(UFortAssetManager_Get) \
	X(UDemoNetDriver_TickFlushInternal) \
	X(AFortAthenaMapInfo_PickSupplyDropLocation) \
	X(AFortDecoTool_ShouldAllowServerSpawnDecoVFT) \
	X(AFortDecoTool_SpawnDecoVFT) \
	X(AFortMission_CreateEncounterSequence) \
	X(ABuildingTrap_FinishTrigger) \
	X(FSpecialActorInitData_Constructor) \
	X(FSpecialActorInitData_Destructor) \
	X(AFortSpecialActorReplicationInfo_AddActorToReplicationList) \
	X(AFortAIDirector_StartEncounterWithoutObjective) \
	X(AFortAthenaMutator_ItemDropOnDeath_SpawnItems) \
	X(AFortAthenaMutator_ItemDropOnDeath_SpawnItems_K2_SpawnPickupInWorld) \
	X(AFortAthenaMutator_ItemDropOnDeath_SpawnItems_K2_SpawnPickupInWorldWithLootTier) \
	X(ABuildingItemCollectorActor_GrantOutputVFT)

namespace ServerOffsets
{
#define CORE_DECLARE_OFFSET(Name) inline uintptr_t Name = 0;
	CORE_OFFSET_LIST(CORE_DECLARE_OFFSET)
#undef CORE_DECLARE_OFFSET
}
